export default [
  { type: 'text', author: `me`, data: { text: `Why don't they have salsa on the table?` } },
  { type: 'text', author: `mattmezza`, data: { text: `What do you need salsa for?` } },
  { type: 'text', author: `me`, data: { text: `Salsa is now the number one condiment in America.` } },
  { type: 'text', author: `mattmezza`, data: { text: `You know why? Because people like to say 'salsa.' 'Excuse me, do you have salsa?' 'We need more salsa.' 'Where is the salsa? No salsa?'` } },
  { type: 'text', author: `me`, data: { text: `You know it must be impossible for a Spanish person to order seltzer and not get salsa. 'I wanted seltzer, not salsa.'` } },
  { type: 'text', author: `mattmezza`, data: { text: `Don't you know the difference between seltzer and salsa?? You have the seltezer after the salsa!` } },
  { type: 'text', author: `me`, data: { text: `See, this should be a show. This is the show. ` } },
  { type: 'text', author: `mattmezza`, data: { text: `What?` } },
  { type: 'text', author: `me`, data: { text: `This. Just talking.` } },
  { type: 'text', author: `mattmezza`, data: { text: `Yeah, right.` } },
  { type: 'text', author: `me`, data: { text: `I'm really serious. I think that's a good idea. ` } },
  { type: 'text', author: `mattmezza`, data: { text: `Just talking? Well what's the show about?` } },
  { type: 'text', author: `me`, data: { text: `It's about nothing.` } },
  { type: 'text', author: `mattmezza`, data: { text: `No story?` } },
  { type: 'system', data: { text: 'You have been transferred to another operator', meta: '04-07-2018 15:57' } },
  { type: 'file', author: `support`, data: { text: `No forget the story. `, file: { name: 'file.mp3', url: '#' } } },
  { type: 'file', author: `me`, data: { text: `What about this one instead?? `, file: { name: 'song.mp3', url: '#' }, meta: '✓✓ Read' } },
  { type: 'text', author: `support`, data: { text: `You've got to have a story. You've got to have a story. You've got to have a story. You've got to have a story. You've got to have a story. You've got to have a story. ` } },
  { type: 'emoji', author: `me`, data: { emoji: `😋` } },
  { type: 'text', author: `me`, data: { text: `Do you read me...`, meta: '✓✓ Read' } },
  { type: 'text', author: `me`, data: { text: `...or not?`, meta: '✓ Delivered' } },
  { type: 'system', data: { text: 'User changed security key', meta: '04-08-2018 15:57' } },
  { type: 'text', author: `support`, data: { text: `What about suggestions?` }, suggestions: ["Looks good!", "It's OK.", "Uhh.. Do I really have to say something?", "This suggestion is way too long for css purpose. Let's make it long... Longer, and more and more.. Never ending."] }
]
